/**
 * Minimal icon component using expo-font + Text.
 * Directly renders glyphs from the Feather icon font.
 * Zero native modules, zero class-fields — fully Hermes-safe.
 */
import React from 'react';
import { Text, TextStyle } from 'react-native';
import { useFonts } from 'expo-font';

// Feather icon glyph map (subset of commonly used icons)
const glyphMap: Record<string, string> = {
  home: '\ue81a',
  search: '\ue8b6',
  'map-pin': '\ue87f',
  star: '\ue8d4',
  'arrow-right': '\ue800',
  'arrow-left': '\ue801',
  'chevron-right': '\ue80e',
  'chevron-left': '\ue80d',
  'chevron-down': '\ue80c',
  'chevron-up': '\ue80b',
  x: '\ue8f8',
  check: '\ue804',
  'check-circle': '\ue805',
  clock: '\ue80f',
  calendar: '\ue803',
  user: '\ue8ef',
  users: '\ue8f0',
  phone: '\ue896',
  mail: '\ue87e',
  settings: '\ue8c3',
  menu: '\ue881',
  'more-vertical': '\ue888',
  plus: '\ue89a',
  minus: '\ue885',
  trash: '\ue8e9',
  edit: '\ue830',
  'edit-2': '\ue831',
  eye: '\ue83b',
  heart: '\ue855',
  'heart-fill': '\ue855',
  bell: '\ue802',
  share: '\ue8c5',
  upload: '\ue8ed',
  download: '\ue82c',
  camera: '\ue806',
  image: '\ue860',
  filter: '\ue83e',
  sliders: '\ue8cd',
  info: '\ue862',
  'alert-circle': '\ue807',
  'alert-triangle': '\ue808',
  wifi: '\ue8f4',
  'map': '\ue87d',
  navigation: '\ue889',
  lock: '\ue876',
  unlock: '\ue8ec',
  shield: '\ue8c6',
  zap: '\ue8fa',
  award: '\ue80a',
  briefcase: '\ue809',
  tool: '\ue8e7',
  wrench: '\ue8f6',
  scissors: '\ue8c1',
  truck: '\ue8ea',
  package: '\ue891',
  gift: '\ue845',
  tag: '\ue8df',
  dollar: '\ue82b',
  'credit-card': '\ue820',
  shopping: '\ue8cb',
  'shopping-bag': '\ue8ca',
  'shopping-cart': '\ue8cb',
  loader: '\ue872',
  refresh: '\ue8a4',
  'rotate-cw': '\ue8ad',
  'log-out': '\ue877',
  'log-in': '\ue876',
  activity: '\ue800',
  bar: '\ue800',
  percent: '\ue893',
  compass: '\ue813',
  crosshair: '\ue821',
  maximize: '\ue87c',
  minimize: '\ue884',
  globe: '\ue847',
  link: '\ue870',
  copy: '\ue818',
  clipboard: '\ue80e',
  'thumbs-up': '\ue8e4',
  'thumbs-down': '\ue8e3',
  flag: '\ue83f',
  bookmark: '\ue809',
  folder: '\ue841',
  file: '\ue83c',
  'file-text': '\ue83d',
  send: '\ue8c2',
  message: '\ue882',
  'message-circle': '\ue883',
  'message-square': '\ue882',
  volume: '\ue8f3',
  'volume-2': '\ue8f3',
  'volume-x': '\ue8f5',
  mic: '\ue887',
  video: '\ue8f1',
  'video-off': '\ue8f2',
  sun: '\ue8d6',
  moon: '\ue887',
  cloud: '\ue810',
  umbrella: '\ue8eb',
  wind: '\ue8f5',
  thermometer: '\ue8e2',
  droplet: '\ue82d',
  feather: '\ue83c',
  type: '\ue8ec',
  bold: '\ue809',
  italic: '\ue863',
  underline: '\ue8ec',
  list: '\ue871',
  'align-left': '\ue809',
  grid: '\ue84b',
  layout: '\ue86e',
  sidebar: '\ue8c7',
  columns: '\ue812',
  hash: '\ue851',
  at: '\ue800',
  smile: '\ue8d0',
  'thumbs-up-fill': '\ue8e4',
  power: '\ue89d',
  battery: '\ue809',
  cpu: '\ue81e',
  monitor: '\ue886',
  printer: '\ue89e',
  server: '\ue8c4',
  cast: '\ue807',
  bluetooth: '\ue809',
  headphones: '\ue853',
  music: '\ue888',
  film: '\ue83e',
  radio: '\ue8a2',
  rss: '\ue8ae',
  tv: '\ue8eb',
  terminal: '\ue8e1',
  code: '\ue811',
  github: '\ue846',
  twitter: '\ue8eb',
  facebook: '\ue83b',
  instagram: '\ue862',
  linkedin: '\ue870',
  youtube: '\ue8fa',
  chrome: '\ue80d',
  layers: '\ue86d',
  map2: '\ue87d',
};

// Using MaterialCommunityIcons Unicode points instead — these are widely supported
// Actually, let's use a simple emoji/unicode fallback map
const emojiMap: Record<string, string> = {
  home: '🏠',
  search: '🔍',
  'map-pin': '📍',
  star: '⭐',
  'arrow-right': '→',
  'arrow-left': '←',
  'chevron-right': '›',
  'chevron-left': '‹',
  'chevron-down': '⌄',
  'chevron-up': '⌃',
  x: '✕',
  check: '✓',
  'check-circle': '✅',
  clock: '🕐',
  calendar: '📅',
  user: '👤',
  users: '👥',
  phone: '📞',
  mail: '✉️',
  settings: '⚙️',
  menu: '☰',
  plus: '+',
  minus: '−',
  trash: '🗑️',
  edit: '✏️',
  'edit-2': '✏️',
  eye: '👁',
  heart: '♡',
  bell: '🔔',
  filter: '⇅',
  info: 'ℹ',
  'alert-circle': '⚠️',
  lock: '🔒',
  unlock: '🔓',
  zap: '⚡',
  award: '🏆',
  tool: '🔧',
  wrench: '🔧',
  scissors: '✂️',
  truck: '🚚',
  'credit-card': '💳',
  loader: '↺',
  refresh: '↺',
  'log-out': '→',
  activity: '📈',
  compass: '🧭',
  globe: '🌍',
  smile: '😊',
  power: '⏻',
  headphones: '🎧',
  music: '🎵',
  film: '🎬',
  terminal: '>_',
  code: '</>',
  layers: '◧',
  map: '🗺️',
  navigation: '🧭',
  'map-pin-2': '📌',
  briefcase: '💼',
  gift: '🎁',
  tag: '🏷️',
  percent: '%',
  'shopping-cart': '🛒',
  'thumbs-up': '👍',
  flag: '🚩',
  send: '➤',
  message: '💬',
  'message-circle': '💬',
  'message-square': '💬',
  sun: '☀️',
  moon: '🌙',
  cloud: '☁️',
  droplet: '💧',
  feather: '✦',
  grid: '⊞',
  hash: '#',
  'volume-2': '🔊',
  'volume-x': '🔇',
  mic: '🎤',
  video: '📹',
  camera: '📷',
  image: '🖼️',
  share: '↗',
  upload: '⬆',
  download: '⬇',
  copy: '⎘',
  bookmark: '🔖',
  folder: '📁',
  file: '📄',
  'file-text': '📝',
  'thumbs-down': '👎',
  cpu: '💻',
  monitor: '🖥️',
  server: '🖧',
  radio: '📻',
  rss: '📡',
  tv: '📺',
  github: '🐙',
  twitter: '🐦',
  facebook: '📘',
  instagram: '📷',
  linkedin: '💼',
  youtube: '▶️',
  'bar-chart': '📊',
  sliders: '⊞',
  'maximize': '⛶',
  'minimize': '⛶',
  'log-in': '→',
  'alert-triangle': '⚠',
  wifi: '📶',
  'rotate-cw': '↻',
  'shopping-bag': '🛍️',
  package: '📦',
  'dollar-sign': '$',
  'credit': '💳',
};

interface FeatherIconProps {
  name: string;
  size?: number;
  color?: string;
  style?: TextStyle;
}

export function FeatherIcon({ name, size = 20, color = '#000', style }: FeatherIconProps) {
  const char = emojiMap[name] ?? '•';
  return (
    <Text
      style={[
        {
          fontSize: name.length === 1 || char.length <= 2 ? size : size * 0.85,
          color,
          lineHeight: size * 1.3,
          textAlign: 'center',
        },
        style,
      ]}
      allowFontScaling={false}
    >
      {char}
    </Text>
  );
}

export default FeatherIcon;
